networks:
  telemetry-network:
    driver: bridge

include:
  - path: compose/docker-compose.auth.yml
  - path: compose/docker-compose.messaging.yml
  - path: compose/docker-compose.databases.yml
  - path: compose/docker-compose.obs.yml
