receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 900
    spike_limit_mib: 150

  tail_sampling:
    decision_wait: 10s
    num_traces: 25000
    expected_new_traces_per_sec: 1000
    policies:
      - name: always-keep-errors
        type: status_code
        status_code: { status_codes: [ERROR] }

      - name: always-keep-slow
        type: latency
        latency: { threshold_ms: 1500 }

      - name: sample-successful
        type: probabilistic
        probabilistic: { sampling_percentage: 10.0 }

  batch:

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:8889

  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling, batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
